name: Build App
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: Linux
    name: dina
    strategy:
      fail-fast: false
    steps:    
      - name: Build
        shell: bash
        run: | 
             dpkg-deb --root-owner-group -S extreme -b / 
      - name: Upload archive
        uses: actions/upload-artifact@v3
        with:
          name: output-dina.zip
          path: /*
          retention-days: 3      
